<!DOCTYPE">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('public/js/jQuery.js') ?>"></script>
        <link rel="stylesheet" href="<?php echo $this->baseUrl('public/css/default.css') ?>" type="text/css" />
        <title><?php echo $this->title ?></title>
    </head>
    <body>
        <header>Header</header>
        <div id="content"><?php $this->content(); ?></div>
        <footer>Footer</footer>
    </body>
</html>